/* CVS $Id: $ */
package net.sf.taverna.t2.provenance.lineageservice.rdf; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from /Users/paolo/Documents/workspace/net.sf.taverna.t2.core/provenanceconnector/src/main/resources/janus.owl 
 * @author Auto-generated by schemagen on 22 Feb 2010 16:00 
 */
public class JanusOntology {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/taverna/janus#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty has_parameter = m_model.createObjectProperty( "http://knoesis.wright.edu/provenir/provenir.owl#has_parameter" );
    
    public static final ObjectProperty derives_from = m_model.createObjectProperty( "http://obofoundry.org/ro/ro.owl#derives_from" );
    
    public static final ObjectProperty part_of = m_model.createObjectProperty( "http://obofoundry.org/ro/ro.owl#part_of" );
    
    public static final ObjectProperty preceded_by = m_model.createObjectProperty( "http://obofoundry.org/ro/ro.owl#preceded_by" );
    
    public static final ObjectProperty has_execution = m_model.createObjectProperty( "http://purl.org/taverna/janus#has_execution" );
    
    public static final ObjectProperty has_parent_workflow = m_model.createObjectProperty( "http://purl.org/taverna/janus#has_parent_workflow" );
    
    public static final ObjectProperty has_source = m_model.createObjectProperty( "http://purl.org/taverna/janus#has_source" );
    
    public static final ObjectProperty has_value_binding = m_model.createObjectProperty( "http://purl.org/taverna/janus#has_value_binding" );
    
    public static final ObjectProperty has_value_type = m_model.createObjectProperty( "http://purl.org/taverna/janus#has_value_type" );
    
    public static final ObjectProperty links_from = m_model.createObjectProperty( "http://purl.org/taverna/janus#links_from" );
    
    public static final DatatypeProperty has_iteration = m_model.createDatatypeProperty( "http://purl.org/taverna/janus#has_iteration" );
    
    public static final DatatypeProperty has_port_order = m_model.createDatatypeProperty( "http://purl.org/taverna/janus#has_port_order" );
    
    public static final DatatypeProperty has_port_type = m_model.createDatatypeProperty( "http://purl.org/taverna/janus#has_port_type" );
    
    public static final DatatypeProperty has_port_value_order = m_model.createDatatypeProperty( "http://purl.org/taverna/janus#has_port_value_order" );
    
    public static final DatatypeProperty has_processor_type = m_model.createDatatypeProperty( "http://purl.org/taverna/janus#has_processor_type" );
    
    public static final DatatypeProperty is_processor_input = m_model.createDatatypeProperty( "http://purl.org/taverna/janus#is_processor_input" );
    
    public static final DatatypeProperty is_top_level = m_model.createDatatypeProperty( "http://purl.org/taverna/janus#is_top_level" );
    
    public static final OntClass data_collection = m_model.createClass( "http://knoesis.wright.edu/provenir/provenir.owl#data_collection" );
    
    public static final OntClass domain_parameter = m_model.createClass( "http://knoesis.wright.edu/provenir/provenir.owl#domain_parameter" );
    
    public static final OntClass process = m_model.createClass( "http://knoesis.wright.edu/provenir/provenir.owl#process" );
    
    public static final OntClass temporal_parameter = m_model.createClass( "http://knoesis.wright.edu/provenir/provenir.owl#temporal_parameter" );
    
    public static final OntClass Data_Sources = m_model.createClass( "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Data_Sources" );
    
    public static final OntClass collection_structure = m_model.createClass( "http://purl.org/taverna/janus#collection_structure" );
    
    public static final OntClass domain_entity = m_model.createClass( "http://purl.org/taverna/janus#domain_entity" );
    
    public static final OntClass port = m_model.createClass( "http://purl.org/taverna/janus#port" );
    
    public static final OntClass port_value = m_model.createClass( "http://purl.org/taverna/janus#port_value" );
    
    public static final OntClass processor_exec = m_model.createClass( "http://purl.org/taverna/janus#processor_exec" );
    
    public static final OntClass processor_spec = m_model.createClass( "http://purl.org/taverna/janus#processor_spec" );
    
    public static final OntClass workflow_run = m_model.createClass( "http://purl.org/taverna/janus#workflow_run" );
    
    public static final OntClass workflow_spec = m_model.createClass( "http://purl.org/taverna/janus#workflow_spec" );
    
    public static final OntClass pathway = m_model.createClass( "http://www.biopax.org/release/biopax-level3.owl#pathway" );
    
    /** <p>A canonical instance of class Gene to associate a semantic type with an instance 
     *  of a port - the specific gene with which the workflow will be run is not at 
     *  this stage of workflow design.</p>
     */
    public static final Individual KEGG = m_model.createIndividual( "http://purl.org/taverna/janus#KEGG", Data_Sources );
    
    public static final Individual ensembl = m_model.createIndividual( "http://purl.org/taverna/janus#ensembl", Data_Sources );
    
    public static final Individual entrez_gene = m_model.createIndividual( "http://purl.org/taverna/janus#entrez_gene", Data_Sources );
    
    /** <p>A canonical instance of class pathway to associate a semantic type with an 
     *  instance of a port - the specific pathway with which the workflow will be 
     *  run is not at this stage of workflow design.</p>
     */
    public static final Individual port_pathway = m_model.createIndividual( "http://purl.org/taverna/janus#port_pathway", pathway );
    
    public static final Individual pubmed = m_model.createIndividual( "http://purl.org/taverna/janus#pubmed", Data_Sources );
    
    public static final Individual uniprot = m_model.createIndividual( "http://purl.org/taverna/janus#uniprot", Data_Sources );
    
}
